Repository ooyala/html5-skin, pull requests merged in 2018-04, with the labels that each got.

#1052 Bugfix/player 3308
  js/controller.js
  tests/html5skin-test.js
Labels: blocker, bug

#1051 Bugfix/player 3289 Language menu is closed by clicking on Language icon after switching to window mode
  .eslintrc
  js/components/closed-caption-multi-audio-menu/closedCaptionMultiAudioMenu.js
  js/components/controlBar.js
  js/skin.js
  package.json
  tests/components/controlBar-test.js
Labels: blocker, bug

#1054 [feature/PLAYER-3147] implement new label functionality
  js/components/closed-caption-multi-audio-menu/helpers.js
  js/components/closed-caption-multi-audio-menu/multiAudioTab.js
  tests/components/closed-caption-multi-audio-menu/helpers-test.js
  tests/components/closed-caption-multi-audio-menu/multiAudioTab-test.js
Labels: feature

#1057 controller eslint
  .eslintrc
  js/controller.js
Labels: enhancement

#1061 [bugfix/PLAYER-634] Add error codes constants
  js/constants/constants.js
  js/views/errorScreen.js
  tests/views/errorScreen-test.js
Labels: bug

#1056 Bugfix/player-3314 to master Language selection closes the CC window
  js/components/closed-caption/closedCaptionPopover.js
  js/components/controlBar.js
  js/components/moreOptionsPanel.js
  js/constants/constants.js
  js/controller.js
  js/skin.js
  js/views/contentScreen.js
  tests/components/closedCaptionPanel-test.js
  tests/html5skin-test.js
  tests/skin-test.js
Labels: blocker, bug
